default:

  #
  # Basic
  #
  server:
    port: 8000

  #
  # Log
  #
  #log:
  #  path: starter-service.log

  #
  # Microservice
  #
  microservice:
    basePath: services
    server:
      name: starter/v1
      dependencies: my/other/service/v1

  #
  # Zookeeper
  #
  zookeeper:
    connectionString: localhost:2181
    retry:
      wait: 1000
      count: 3
